TrendCart/Accounts/urls.py
from django.contrib import admin
from django.urls import path
from Accounts import views
app_name="Accounts"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup',views.signup,name="signup"),
    path('accounts/login/',views.user_login,name="login"),
    path('user_logout',views.user_logout,name="user_logout"),
    path('user_home',views.user_home,name="user_home"),
    path('admin_dashboard',views.admin_dashboard,name="admin_dashboard"),
    path('user_list',views.user_list,name="user_list"),
    path('user_detail/<int:user_id>', views.user_detail, name='user_detail'),
    path('user_detail/deactivate/<int:user_id>', views.deactivate_user, name='deactivate_user'),
    path('user_detail/activate/<int:user_id>', views.activate_user, name='activate_user'),
    path('user_detail/delete/<int:user_id>', views.delete_user, name='delete_user'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('profile', views.profile, name='profile'),
    path('update_profile/<int:p>', views.update_profile, name='update_profile'),
    path('change_password/<int:p>', views.change_password, name='change_password'),
    # path('product_detail/<int:p>', views.product_detail, name='product_detail'),
    # path('<int:user_id>/deactivate/', views.deactivate_user, name='deactivate_user'),
    # path('<int:user_id>/delete/', views.delete_user, name='delete_user'),
]

TrendCart/Cart/urls.py
from django.contrib import admin
from django.urls import path
from Cart import views
app_name="Cart"
urlpatterns = [
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),



]

TrendCart/Category/urls.py
from django.contrib import admin
from django.urls import path
from Category import views
app_name="Category"
urlpatterns = [
    path('',views.addcategory, name="addcategory"),
    path('/viewmaincategory',views.viewmaincategory,name="viewmaincategory"),
    path('/deletemaincategory',views.deletemaincategory,name="deletemaincategory"),
    path('/delmaincategory/<int:p>', views.delmaincategory, name="delmaincategory"),
    path('/viewupdatemaincategory', views.viewupdatemaincategory, name="viewupdatemaincategory"),
    path('/updatemaincategory/<int:p>', views.updatemaincategory, name="updatemaincategory"),
    path('/updatemaincategory/updaterecord/<int:p>',views.updaterecord, name='updaterecord'),
    path('/addsubcategory', views.addsubcategory, name="addsubcategory"),
    path('/viewsubcategory', views.viewsubcategory, name="viewsubcategory"),
    path('/deletesubcategory', views.deletesubcategory, name="deletesubcategory"),
    path('/delsubcategory/<int:p>', views.delsubcategory, name="delsubcategory"),
    path('/viewupdatesubcategory', views.viewupdatesubcategory, name="viewupdatesubcategory"),
    path('/updatesubcategory/<int:p>', views.updatesubcategory, name="updatesubcategory"),
    path('/updatesubcategory/updatesubrecord/<int:p>', views.updatesubrecord, name='updatesubrecord'),

]

TrendCart/Order/urls.py
from django.contrib import admin
from django.urls import path
from Order import views
app_name="Order"
urlpatterns = [
    path('/place_order/', views.place_order, name='place_order'),
    path('order_history/', views.order_history, name='order_history'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_detail/<int:p>', views.order_detail, name='order_detail'),
    path('order_view/<int:p>', views.order_view, name='order_view'),
    path('/update_order_status/<int:p>', views.update_order_status, name='update_order_status'),
    path('order/success/<int:order_id>/', views.order_success, name='order_success'),

]

TrendCart/Product/urls.py
from django.contrib import admin
from django.urls import path
from Product import views
app_name="Product"
urlpatterns = [
    path('/addproduct',views.addproduct, name="addproduct"),
    path('/viewproducts',views.viewproducts,name="viewproducts"),
    path('/deleteproduct',views.deleteproduct,name="deleteproduct"),
    path('/delproduct/<int:p>', views.delproduct, name="delproduct"),
    path('/viewupdateproduct', views.viewupdateproduct, name="viewupdateproduct"),
    path('/updateproducts/<int:p>', views.updateproducts, name="updateproducts"),
    path('/updateproducts/updateproductrecord/<int:p>',views.updateproductrecord, name='updateproductrecord'),
    path('/productlist/', views.product_list, name='product_list'),
    # path('/mobilecomputer_productlist', views.mobilecomputer_productlist, name='mobilecomputer_productlist'),
    path('/tv_app_ele_productlist/<int:p>', views.tv_app_ele_productlist, name='tv_app_ele_productlist'),
    path('/product_detail/<int:p>', views.product_detail, name='product_detail'),
    path('admin/out_of_stock/', views.out_of_stock_products, name='out_of_stock_products'),

    # path('/trending_item/<int:p>', views.trending_item, name='trending_item'),


    # path('/addsubcategory', views.addsubcategory, name="addsubcategory"),
    # path('/viewsubcategory', views.viewsubcategory, name="viewsubcategory"),
    # path('/deletesubcategory', views.deletesubcategory, name="deletesubcategory"),
    # path('/delsubcategory/<int:p>', views.delsubcategory, name="delsubcategory"),
    # path('/viewupdatesubcategory', views.viewupdatesubcategory, name="viewupdatesubcategory"),
    # path('/updatesubcategory/<int:p>', views.updatesubcategory, name="updatesubcategory"),
    # path('/updatesubcategory/updatesubrecord/<int:p>', views.updatesubrecord, name='updatesubrecord'),

]

TrendCart/TrendCart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Accounts.urls')),
    path('category',include('Category.urls')),
    path('product',include('Product.urls')),
    path('cart',include('Cart.urls')),
    path('order',include('Order.urls')),
    path('search',include('Search.urls')),
    path('email/',include('Email.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrendCart/Cart/models.py
from django.db import models
from Product.models import Product
# from django.contrib.auth.models import User
from Accounts.models import CustomUser

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

# class Order(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     username = models.CharField(max_length=100)
#     email = models.EmailField()
#     address = models.CharField(max_length=255)
#     address2 = models.CharField(max_length=255, blank=True, null=True)
#     country = models.CharField(max_length=100)
#     state = models.CharField(max_length=100)
#     zip_code = models.CharField(max_length=20)
#     payment_method = models.CharField(max_length=50)
#     card_name = models.CharField(max_length=100)
#     card_number = models.CharField(max_length=20)
#     expiration = models.CharField(max_length=5)
#     cvv = models.CharField(max_length=4)
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return f"Order {self.id}"
#
# class OrderItem(models.Model):
#     order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
#     product_name = models.CharField(max_length=100)
#     product_price = models.DecimalField(max_digits=10, decimal_places=2)
#     quantity = models.PositiveIntegerField(default=1)
#
#     def __str__(self):
#         return f"{self.product_name} (x{self.quantity})"
#


# class Order(models.Model):
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)
#     total_price = models.DecimalField(max_digits=10, decimal_places=2)
#
#     def __str__(self):
#         return f"Order {self.id} by {self.user.username}"
#
# class OrderItem(models.Model):
#     order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=1)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#
#     def __str__(self):
#         return f"{self.quantity} of {self.product.name}"

# Create your models here.
#
# class Order(models.Model):
#     product=models.ForeignKey(Product,on_delete=models.CASCADE)
#     no_of_items=models.IntegerField()
#     user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
#     ordered_date=models.DateTimeField(auto_now_add=True)
#     address=models.TextField()
#     phone=models.TextField()
#     order_status=models.CharField(max_length=20,default="pending")
#     delivery_status=models.CharField(max_length=20,default="pending")
#     def __str__(self):
#         return self.product.name
#
# class Account(models.Model):
#     acctnum=models.IntegerField()
#     accttype=models.CharField(max_length=20)
#     amount=models.IntegerField()
#     def __str__(self):
#         return str(self.acctnum)

TrendCart/Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from Product.models import Product
from Cart.models import CartItem
@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_item, created = CartItem.objects.get_or_create(user=request.user, product=product)

    if created:
        if product.stock > 0:
            cart_item.quantity = 1
            cart_item.save()
        else:
            messages.error(request, "This product is out of stock.")
    else:
        if cart_item.quantity < product.stock:
            cart_item.quantity += 1
            cart_item.save()
        else:
            messages.error(request, "You have reached the maximum available stock for this product.")

    return redirect('Cart:cart')  #
@login_required
def cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    cart_items_count = cart_items.count()
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    in_stock_items = any(item.product.stock > 0 for item in cart_items)
    return render(request, 'cart.html', {
        'cart_items': cart_items,
        'total_price': total_price,
        'cart_items_count': cart_items_count,
        'in_stock_items': in_stock_items,
    })



@login_required
def update_cart(request, item_id):
    item = get_object_or_404(CartItem, id=item_id, user=request.user)
    product = item.product

    if request.method == "POST":
        action = request.POST['action']
        if action == 'increase':
            if item.quantity < product.stock:
                item.quantity += 1
            else:
                messages.error(request, "Not enough stock available.")
        elif action == 'decrease' and item.quantity > 1:
            item.quantity -= 1
        item.save()

    return redirect('Cart:cart')


@login_required
def remove_from_cart(request, item_id):
    item = get_object_or_404(CartItem, id=item_id, user=request.user)
    item.delete()
    return cart(request)

TrendCart/templates/deletesubcategory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:150px">

<div class="container mt-5">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
          <th scope="col">Category Name</th>
        <th scope="col">Sub Category Name</th>
        <th scope="col">Sub Category Description</th>
                  <th scope="col">Sub Category Cover</th>

           <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
     {% for i in ds %}

      <tr>
          <td>{{i.maincategory}}</td>
        <td>{{i.sname}}</td>
        <td>{{i.sdesc}}</td>
             <td><img src="{{i.simages.url}}" alt="Sub Category Cover" style="width: 50px; height: 50px;"></td>
          <td><a href="{% url 'Category:delsubcategory' i.id %}" class="btn btn-danger" >Delete</td>
      </tr>
{% endfor %}
      <!-- Add more rows as needed -->
    </tbody>
  </table>
</div>

</div>


{% endblock %}

TrendCart/templates/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .bg {
        /* Full height */
        height: 100%;
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .reset-confirm-container {
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .reset-confirm-card {
        background: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 100%;
        max-width: 500px;
        text-align: center;
    }
</style>

<body>
    <div class="bg mb-5 mt-5">
        <div class="container reset-confirm-container">
            <div class="reset-confirm-card">
                <h2 class="mb-4">Password Reset Request</h2>
                <p>An email with instructions to reset your password has been sent to your registered email address.</p>
                <p>If you don't receive an email within a few minutes, please check your spam folder.</p>
                <p>Return to <a href="{% url 'Accounts:login' %}">login page</a></p>
            </div>
        </div>
    </div>
</body>
{% endblock %}

TrendCart/templates/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Request</title>
    <!-- Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="card p-4">
            <h2 class="text-center mb-4">Password Reset Request</h2>
            <p>An email with instructions to reset your password has been sent to your registered email address.</p>
            <p>If you don't receive an email within a few minutes, please check your spam folder.</p>
            <p>Return to <a href="{% url 'Accounts:login' %}">login page</a></p>
        </div>
    </div>
</body>
</html>

TrendCart/templates/place_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load static %}
<body>



<div class="container">
    <div class="py-5 text-center">
        <h2>Checkout form</h2>
        <p class="lead">Please fill in your details to complete the purchase.</p>
    </div>

    <div class="row">
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Shipping Address</h4>
            <form method="POST" action="{% url 'Order:place_order' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">First name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Last name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" placeholder="" value="" required>
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="email">Email <span class="text-muted">*</span></label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com">
                    <div class="invalid-feedback">
                        Please enter a valid email address for shipping updates.
                    </div>
                </div>

                <div class="mb-3">
                    <label for="address">Address</label>
                    <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required>
                    <div class="invalid-feedback">
                        Please enter your shipping address.
                    </div>
                </div>

                <div class="mb-3">
                    <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
                    <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment or suite">
                </div>

                <div class="row">
                    <div class="col-md-5 mb-3">
                        <label for="country">Country</label>
                        <select class="custom-select d-block w-100" id="country" name="country" required>
                            <option value="">Choose...</option>
                            <option>India</option>
                        </select>
                        <div class="invalid-feedback">
                            Please select a valid country.
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="state">State</label>
                        <select class="custom-select d-block w-100" id="state" name="state" required>
                            <option value="">Choose...</option>
                            <option>Kerala</option>
                        </select>
                        <div class="invalid-feedback">
                            Please provide a valid state.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="zip">Zip</label>
                        <input type="text" class="form-control" id="zip" name="zip" placeholder="" required>
                        <div class="invalid-feedback">
                            Zip code required.
                        </div>
                    </div>
                </div>

                <hr class="mb-4">

<!--                <div class="custom-control custom-checkbox">-->
<!--                    <input type="checkbox" class="custom-control-input" id="same-address">-->
<!--                    <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>-->
<!--                </div>-->
<!--                <div class="custom-control custom-checkbox">-->
<!--                    <input type="checkbox" class="custom-control-input" id="save-info">-->
<!--                    <label class="custom-control-label" for="save-info">Save this information for next time</label>-->
<!--                </div>-->

<!--                <hr class="mb-4">-->

                <h4 class="mb-3">Payment</h4>

                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                        <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" value="Credit card" checked required>
                        <label class="custom-control-label" for="credit">Credit card</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" value="Debit card" required>
                        <label class="custom-control-label" for="debit">Debit card</label>
                    </div>
<!--                    <div class="custom-control custom-radio">-->
<!--                        <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" value="Paypal" required>-->
<!--                        <label class="custom-control-label" for="paypal">Paypal</label>-->
<!--                    </div>-->
                </div>

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="cc-name">Name on card</label>
                        <input type="text" class="form-control" id="cc-name" name="cc-name" placeholder="" required>
                        <small class="text-muted">Full name as displayed on card</small>
                        <div class="invalid-feedback">
                            Name on card is required
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="cc-number"> Card number</label>
                        <input type="text" class="form-control" id="cc-number" name="cc-number" placeholder="" required>
                        <div class="invalid-feedback">
                            Credit card number is required
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3 mb-3">
                        <label for="cc-expiration">Expiration</label>
                        <input type="text" class="form-control" id="cc-expiration" name="cc-expiration" placeholder="" required>
                        <div class="invalid-feedback">
                            Expiration date required
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="cc-cvv">CVV</label>
                        <input type="text" class="form-control" id="cc-cvv" name="cc-cvv" placeholder="" required>
                        <div class="invalid-feedback">
                            Security code required
                        </div>
                    </div>
                </div>

                <!-- Hidden inputs for cart items -->
                {% for item in cart_items %}
                <input type="hidden" name="cart_items" value="{{ item.product.name }},{{ item.product.price }},{{ item.quantity }}">
                {% endfor %}

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">PLACE ORDER</button>
            </form>
        </div>

        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Order Summary</span>
                <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
            </h4>
            <ul class="list-group mb-3">
                {% for item in cart_items %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ item.product.name }}</h6>
                        <small class="text-muted">{{ item.product.description }}</small>
                    </div>
                    <span class="text-muted">{{ item.product.price }}</span>
                </li>
                {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>Amount Payable </span>
                    <strong>{{ total_amount }}</strong>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
{% endblock %}

TrendCart/templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Search Results - TrendCart{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Search Results</h1>
    {% if query %}
        <p>Results for "{{ query }}":</p>
    {% endif %}
    {% if results %}
        <div class="row">
            {% for product in results %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ product.images.url  }}" class="card-img-top" alt="{{ product.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.desc|truncatewords:20 }}</p>
                            <a href="{% url 'Product:product_detail' product.id %}" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No results found for your search query.</p>
    {% endif %}
</div>
{% endblock %}

TrendCart/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        .bg {
            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .login-container {
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .login-form {
            background: rgba(255, 255, 255, 0.8);
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 500px;
        }

        .login-form a {
            margin-right: 10px;
        }

        .alert-custom-error {
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
        }

        .alert-custom-success {
            color: #3c763d;
            background-color: #dff0d8;
            border-color: #d6e9c6;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
    </style>

<body>
    <div class="bg mb-5 mt-5">
        <div class="container login-container">
            <form class="login-form" method="POST">
                {% csrf_token %}
                <h2 class="text-center">Register</h2>

                {% if messages %}
                    <div>
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <div class="alert alert-custom-error">{{ message }}</div>
                            {% elif message.tags == 'success' %}
                                <div class="alert alert-custom-success">{{ message }}</div>
                            {% else %}
                                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}

                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="firstName" placeholder="Enter first name" required>
                </div>
                <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="lastName" placeholder="Enter last name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email ID</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email ID" required>
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="number" class="form-control" id="phone" name="phonenumber" placeholder="Enter phone number" required>
                </div>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
                </div>
                <div class="form-group">
                    <label for="confirm_password">Confirm Password</label>
                    <input type="password" class="form-control" id="confirm_password" name="confirmPassword" placeholder="Confirm password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Register</button>
                <div class="form-group mt-3 text-center">
                    <a href="{% url 'Accounts:login' %}">Already have an account? Login Now</a>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

TrendCart/templates/viewupdatesubcategory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:150px">

<div class="container mt-5">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
          <th scope="col">Category Name</th>
        <th scope="col">Sub Category Name</th>
        <th scope="col">Sub Category Description</th>
        <th scope="col">Sub Category Cover</th>
           <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
     {% for i in v %}

      <tr>
          <td>{{i.maincategory}}</td>
        <td>{{i.sname}}</td>
        <td>{{i.sdesc}}</td>
          <td><img src="{{i.simages.url}}" alt="Sub Category Cover" style="width: 50px; height: 50px;"></td>

          <td><a href="{% url 'Category:updatesubcategory' i.id %}" class="btn btn-danger" >Edit</td>
      </tr>
{% endfor %}
      <!-- Add more rows as needed -->
    </tbody>
  </table>
</div>

</div>


{% endblock %}